# ===================================================================
# Konfigurationsprofil für eine gründliche, 45-minütige Erfassung
# ===================================================================

# --- Capture Settings ---
capture:
  # Standard-Interface, das verwendet wird, wenn --iface nicht angegeben wird.
  # Lassen Sie dies leer, um die interaktive Auswahl zu nutzen, oder tragen Sie
  # Ihr bevorzugtes Monitor-Interface ein (z.B. "wlan0mon").
  interface: "mon0"

  # Gesamtdauer der Erfassung in Sekunden (45 Minuten = 2700 Sekunden)
  duration: 2700

  # Name der PCAP-Datei, die gespeichert wird, wenn --pcap angegeben wird.
  # Wird durch --project oder --outdir in das entsprechende Verzeichnis verschoben.
  pcap_file: "capture.pcap"


# --- Database Settings ---
database:
  # Standardname für die Event-Datenbank, wenn --db nicht angegeben wird.
  path: "events1.db"
  # Standardname für die Label-Datenbank.
  label_db: "labels1.db"


# --- Advanced Scanning Features ---
# Hier werden alle neuen, intelligenten Scan-Funktionen aktiviert.
scanning:
  # Aktiviert den zweistufigen Scan: Zuerst eine breite Suche, dann eine
  # gezielte Überwachung der aktivsten Kanäle.
  adaptive_scan_enabled: true

  # Dauer der initialen "Discovery"-Phase in Sekunden.
  # 120 Sekunden (2 Minuten) sind ein guter Wert, um die meisten aktiven
  # Geräte in der Umgebung zu entdecken.
  adaptive_scan_discovery_s: 120

  # Anzahl der besten Kanäle, auf die sich das Tool in der zweiten Phase
  # konzentrieren soll.
  adaptive_scan_top_n_channels: 6

  # Wie stark die Top-Kanäle priorisiert werden. Ein Wert von 3 bedeutet,
  # dass sie 3x so oft gescannt werden wie die restlichen Kanäle.
  adaptive_scan_priority_weight: 3

  # Kanalbandbreite für den 5-GHz-Bereich. "80MHz" ist ein guter Kompromiss
  # zwischen Abdeckung und Kompatibilität der Hardware.
  bandwidth_5ghz: "80MHz"

  # Kanalbandbreite für den 2,4-GHz-Bereich. "HT40" erfasst mehr Daten,
  # wenn benachbarte Kanäle frei sind.
  bandwidth_2_4ghz: "HT40"